version: "3"

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data
 
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  llm-repair-them-all:
    image: andre15silva/llm-repair-them-all
    restart: no
    # keeps the container waiting forever, so that we can exec a shell into it
    entrypoint: tail -F anything

volumes:
  db:
    driver: local