#!/usr/bin/env bash

# Project to run under
#SBATCH -A SNIC2022-5-596 -p alvis
#SBATCH -J {job_name}
#SBATCH -N 1 --gpus-per-node={gpu_type}:{gpu_number}
#SBATCH --time={job_time}
#SBATCH --output={job_name}-%j.out
#SBATCH --error={job_name}-%j.err

python {script}