name: lint
on: [push]

jobs:
  lint:
    strategy:
      matrix:
        src-dir: ["./elleelleaime", "./tests"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Run linter
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: ${{ matrix.src-dir }}
          version: "23.3.0"
